### ISSUE TITLE
TROPIND has one point in the Arctic Ocean 

### ISSUE THREAD

**Issue by b-r-hamilton** [ggebbie/TMI.jl#123]
![Screenshot from 2023-07-05 15-27-36](https://github.com/ggebbie/TMI.jl/assets/57123440/ccd83300-97e0-42ea-8450-3b2942f56771)
There's also one point in the East China Sea that I feel like I would call Pacific, but that one is more debateable. I'm only noticing this under intense scrutiny - probably not a massive issue, but if .nc files the regions are sourced from get regenerated, might be worth fixing.

**Comment by ggebbie** [comment]
Thank you! Which version is this?  

The White Sea problem was fixed at one point many years ago, but perhaps it was only fixed for one of the resolutions.

**Comment by b-r-hamilton** [comment]
This is modern_180x90x33_GH11_GH12
