### ISSUE TITLE
Vector multiplication error in L2188 in TMI.jl

### ISSUE THREAD

**Issue by xabi94davi** [ggebbie/TMI.jl#131]
No method matching *(::Vector{Float64}, ::Vector{Float64})

So far the code does not allow multiplication when `Q-` and `uvec` are both vectors.

**Comment by ggebbie** [comment]
Mathematically the multiplication of two vectors is not defined. 

Elementwise multiplication is fine: `Q.*uvec`

Alternatively can be a Diagonal matrix and then matrix-vector multiplication is well-defined.
